"use client";

import React from "react";
import { HelpCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "./ui/accordion";

interface FAQItem {
  value: string;
  question: string;
  answer: React.ReactNode;
}

const FAQSection: React.FC<{ className?: string }> = ({ className }) => {
  const faq: FAQItem[] = [
    {
      value: "item-1",
      question: "How to stake?",
      answer: (
        <>
          Select your preferred token (STRK or BTC), enter the amount you want
          to stake, optionally choose a DeFi protocol for additional yield, and
          click the Stake button. You'll receive liquid staking tokens (xSTRK or
          xBTC) that represent your staked position.
        </>
      ),
    },
    {
      value: "item-2",
      question: "How to unstake?",
      answer: (
        <>
          To unstake, navigate to the Unstake tab, enter the amount of liquid
          staking tokens (xSTRK or xBTC) you want to unstake, and click the
          Unstake button. Your tokens will be queued for withdrawal.
        </>
      ),
    },
    {
      value: "item-3",
      question: "What is liquid staking?",
      answer: (
        <>
          Liquid staking allows you to stake your tokens while maintaining
          liquidity. You receive liquid staking tokens (LSTs) that represent
          your staked position and can be used in DeFi protocols or traded while
          still earning staking rewards.
        </>
      ),
    },
    {
      value: "item-4",
      question: "Where does the yield come from?",
      answer: (
        <>
          The yield comes from staking rewards generated by validators on the
          Starknet network. Additionally, you can earn extra yield by deploying
          your liquid staking tokens to supported DeFi protocols.
        </>
      ),
    },
    {
      value: "item-5",
      question: "What are Security and Audits of the protocol?",
      answer: (
        <>
          Our protocol has undergone comprehensive security audits by leading
          blockchain security firms. We maintain strict security standards and
          regularly update our smart contracts to ensure the safety of user
          funds. Detailed audit reports are available in our documentation.
        </>
      ),
    },
  ];

  return (
    <div
      className={cn(
        "w-full bg-white px-2 py-4 shadow-sm lg:p-4",
        "rounded-[14px] border border-[#E5E8EB]",
        "shadow-[0_1px_2px_-1px_#0000001A,_0_1px_3px_0_#0000001A]",
        className,
      )}
    >
      <div className="mb-4 flex items-center gap-2">
        <HelpCircle className="h-5 w-5 text-[#0D5F4E]" />
        <h3 className="text-sm uppercase text-[#0D5F4E]">
          Frequently Asked Questions
        </h3>
      </div>
      <Accordion type="single" collapsible defaultValue="item-1">
        {faq.map((item, i) => (
          <AccordionItem
            key={item.value}
            value={item.value}
            className={
              i < faq.length - 1 ? "border-b border-[#E5E8EB]" : "border-b-0"
            }
          >
            <AccordionTrigger
              className={cn(
                "text-left text-sm text-[#1A1F24] hover:no-underline",
                {
                  "[&>svg]:text-[#17876D] data-[state=open]:[&>svg]:text-[#17876D]":
                    i === 0,
                  "[&>svg]:text-[#6B7780] data-[state=open]:[&>svg]:text-[#17876D]":
                    i !== 0,
                },
              )}
            >
              {item.question}
            </AccordionTrigger>
            <AccordionContent className="text-xs text-[#6B7780]">
              {item.answer}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
};

export default FAQSection;
