"use client";

import React from "react";
import { HelpCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "./ui/accordion";
import Link from "next/link";

interface FAQItem {
  value: string;
  question: string;
  answer: React.ReactNode;
}

const FAQSection: React.FC<{ className?: string }> = ({ className }) => {
  const faq: FAQItem[] = [
    {
      value: "item-1",
      question: "How to stake?",
      answer: (
        <>
          Select your preferred token (STRK or BTC), enter the amount you want
          to stake, optionally choose a DeFi protocol for additional yield, and
          click the Stake button. {"You'll"} receive liquid staking tokens (xSTRK or
          xyBTC) that represent your staked position.
        </>
      ),
    },
    {
      value: "item-2",
      question: "How to unstake?",
      answer: (
        <>
          To unstake, navigate to the Unstake tab, enter the amount of liquid
          staking tokens (xSTRK or xyBTC) you want to unstake, and click the
          Unstake button. Select {"\"Use DEX\""} or {"\"Use Endur\""} to choose your preferred withdrawal method. DEX is instantaneous but price is usually less than {"Endur's"}. With Endur, Your tokens will be queued for withdrawal and may take upto 7-8 days.
        </>
      ),
    },
    {
      value: "item-3",
      question: "What is liquid staking vs Native staking?",
      answer: (
        <>
          When you native stake on Starknet, your tokens are locked and to withdraw, you may need to wait for 7 days. Liquid staking allows you to stake your tokens while maintaining liquidity.
          If you need liquidity immediately, with liquid staking, you have the optionality to redeem them instantly via DEX. Additionally, the LSTs can be used in DeFi protocols for additional yield or as collateral for borrowing.
        </>
      ),
    },
    {
      value: "item-4",
      question: "Where does the yield come from?",
      answer: (
        <>
          The yield comes from staking rewards generated by validators on the
          Starknet network. Endur delegates your staked tokens to validators on your behalf.
        </>
      ),
    },
    {
      value: "item-5",
      question: "What are Security and Audits of the protocol?",
      answer: (
        <>Audit reports are available in our documentation <Link href="https://docs.endur.fi/docs/security" target="_blank" className="underline">here.</Link> 
          {" "}Additionally, Endur is governed by a 3/4 multisig controlled by the Unwrap Labs and Karnot team. Further, Endur is looking to perform more security audits, reduce permissioned functions and add real time risk monitoring (e.g. Hypernative) by Q1 2026.
        </>
        // <>
        //   Our protocol has undergone comprehensive security audits by leading
        //   blockchain security firms. We maintain strict security standards and
        //   regularly update our smart contracts to ensure the safety of user
        //   funds. Detailed audit reports are available in our documentation.
        // </>
      ),
    },
  ];

  return (
    <div
      className={cn(
        "w-full bg-white px-2 py-4 shadow-sm lg:p-4",
        "rounded-[14px] border border-[#E5E8EB]",
        "shadow-[0_1px_2px_-1px_#0000001A,_0_1px_3px_0_#0000001A]",
        className,
      )}
    >
      <div className="mb-4 flex items-center gap-2">
        <HelpCircle className="h-5 w-5 text-[#0D5F4E]" />
        <h3 className="text-sm uppercase text-[#0D5F4E]">
          Frequently Asked Questions
        </h3>
      </div>
      <Accordion type="single" collapsible defaultValue="item-1">
        {faq.map((item, i) => (
          <AccordionItem
            key={item.value}
            value={item.value}
            className={
              i < faq.length - 1 ? "border-b border-[#E5E8EB]" : "border-b-0"
            }
          >
            <AccordionTrigger
              className={cn(
                "text-left text-sm text-[#1A1F24] hover:no-underline",
                {
                  "[&>svg]:text-[#17876D] data-[state=open]:[&>svg]:text-[#17876D]":
                    i === 0,
                  "[&>svg]:text-[#6B7780] data-[state=open]:[&>svg]:text-[#17876D]":
                    i !== 0,
                },
              )}
            >
              {item.question}
            </AccordionTrigger>
            <AccordionContent className="text-xs text-[#6B7780]">
              {item.answer}
            </AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </div>
  );
};

export default FAQSection;
